XDP_TARGETS  := ebpf/lpm_prog
XDP_TARGETS  := ebpf/forward_prog
USER_TARGETS := control/xdp_loader
USER_TARGETS += control/xdp_stats
USER_TARGETS += control/xdp_reader

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common/

include $(COMMON_DIR)/common.mk
