/*
 * BigBro/2021
 */

#ifndef __COMMON_KERN_USER_H
#define __COMMON_KERN_USER_H

#define SESSION_NAT_INNER_MAP_NAME			"session_nat_table_inner"

#define __XDP_ACTION_MAX 		(XDP_REDIRECT + 1)
#define MAX_SUPPORTED_CPUS 		128

struct pkt_stats {
	__u64 rx_packets;
	__u64 rx_bytes;
};

enum {
	STATS_GLOBAL_PKT_ALL,
	STATS_GLOBAL_PKT_VLAN,
	STATS_GLOBAL_PKT_VLAN_FROM_CLIENT,
	STATS_GLOBAL_PKT_VLAN_FROM_SERVER,
	STATS_GLOBAL_PKT_OTHER_VLAN,
	STATS_GLOBAL_PKT_L3_UNKNOWN,
	STATS_GLOBAL_PKT_ARP,
	STATS_GLOBAL_PKT_IPv4_UNKNOWN,
	STATS_GLOBAL_PKT_IPv4_HEADER_INVALID,
	STATS_GLOBAL_PKT_ICMPv4_ECHO,
	STATS_GLOBAL_PKT_ICMPv4_ECHOREPLY,
	STATS_GLOBAL_PKT_ICMPv4_OTHER,
	STATS_GLOBAL_PKT_TCPv4,
	STATS_GLOBAL_PKT_UDPv4,
	STATS_GLOBAL_PKT_IPv6_UNKNOWN,
	STATS_GLOBAL_PKT_IPv6_HEADER_INVALID,
	STATS_GLOBAL_PKT_ICMPv6_ECHO,
	STATS_GLOBAL_PKT_ICMPv6_ECHOREPLY,
	STATS_GLOBAL_PKT_ICMPv6_OTHER,
	STATS_GLOBAL_PKT_TCPv6,
	STATS_GLOBAL_PKT_UDPv6,
	__STATS_GLOBAL_PKT_MAX
};

enum {
	STATS_GLOBAL_VALIDITY_NONE_TAG,
	STATS_GLOBAL_VALIDITY_UNKNOWN_TAG,
	STATS_GLOBAL_VALIDITY_ETHERNET_HEADER_MALFORM,
	STATS_GLOBAL_VALIDITY_IPv4_HEADER_MALFORM,
	STATS_GLOBAL_VALIDITY_UDP_HEADER_MALFORM,
	STATS_GLOBAL_VALIDITY_IPv6_HEADER_MALFORM,
	__STATS_GLOBAL_VALIDITY_MAX
};

#endif
