/*
 * BigBro/2021
 */

#ifndef __COMMON_KERN_USER_H
#define __COMMON_KERN_USER_H

struct pkt_stats {
	__u64 rx_packets;
	__u64 rx_bytes;
};

enum {
	STATS_GLOBAL_PKT_VLAN,
	STATS_GLOBAL_PKT_L3_UNKNOWN,
	STATS_GLOBAL_PKT_ARP,
	STATS_GLOBAL_PKT_IPv4_UNKNOWN,
	STATS_GLOBAL_PKT_ICMPv4_ECHO,
	STATS_GLOBAL_PKT_ICMPv4_ECHOREPLY,
	STATS_GLOBAL_PKT_ICMPv4_OTHER,
	STATS_GLOBAL_PKT_TCPv4,
	STATS_GLOBAL_PKT_UDPv4,
	STATS_GLOBAL_PKT_IPv6_UNKNOWN,
	STATS_GLOBAL_PKT_ICMPv6_ECHO,
	STATS_GLOBAL_PKT_ICMPv6_ECHOREPLY,
	STATS_GLOBAL_PKT_ICMPv6_OTHER,
	STATS_GLOBAL_PKT_TCPv6,
	STATS_GLOBAL_PKT_UDPv6,
	__STATS_GLOBAL_PKT_MAX
};

enum {
	STATS_GLOBAL_VALIDITY_IPv4_IHL_ERROR,
	STATS_GLOBAL_VALIDITY_IPv6_HEADER_MALFORMATION,
	__STATS_GLOBAL_VALIDITY_MAX
};

#endif
