#ifndef __COMMON_KERN_USER_H
#define __COMMON_KERN_USER_H

#define MY_MAP_REUSEPORT_SIZE 	10
#define MY_MAP_STATS_SIZE 		(5 + 1)
#define MY_MAP_TOTAL_SIZE 		(MY_MAP_REUSEPORT_SIZE + MY_MAP_STATS_SIZE)

#define MY_MAP_STATS_SOCKET1	(MY_MAP_REUSEPORT_SIZE + 0)
#define MY_MAP_STATS_SOCKET2	(MY_MAP_REUSEPORT_SIZE + 1)
#define MY_MAP_STATS_SOCKET3	(MY_MAP_REUSEPORT_SIZE + 2)
#define MY_MAP_STATS_SOCKET4	(MY_MAP_REUSEPORT_SIZE + 3)
#define MY_MAP_STATS_SOCKET5	(MY_MAP_REUSEPORT_SIZE + 4)
#define MY_MAP_STATS_FAILURE	(MY_MAP_REUSEPORT_SIZE + 5)

#endif
