XDP_TARGETS := sk_filter_kern
USER_TARGETS := sk_filter_user

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common/

include $(COMMON_DIR)/common.mk
COMMON_OBJS := $(COMMON_DIR)/common_params.o
